export const adminConfig = {
  toast: {
    created: "Creado exitosamente.",
    updated: "Guardado correctamente.",
    saved: "Guardado correctamente.",
  },
  printLists: {
    navLabel: "Impresiones",
    href: "/admin/impresiones",
    eyebrow: "Landing",
    title: "Impresiones",
    description:
      "Edita el nombre y el valor de cada tamaño. Las fotos y los títulos de la landing no cambian.",
    nameLabel: "Nombre",
    valueLabel: "Valor",
    addLabel: "Agregar fila",
    removeLabel: "Quitar",
    saveLabel: "Guardar cambios",
    namePlaceholder: "10×15",
    valuePlaceholder: "20.000",
  },
  conditions: {
    navLabel: "Condiciones",
    href: "/admin/condiciones",
    eyebrow: "Landing",
    title: "Condiciones",
    description:
      "Edita el título y el texto de cada condición. El encabezado de la sección no cambia.",
    titleLabel: "Título",
    bodyLabel: "Texto",
    addLabel: "Agregar condición",
    removeLabel: "Quitar",
    saveLabel: "Guardar cambios",
    titlePlaceholder: "Galería",
    bodyPlaceholder: "Describe la condición…",
  },
  liveEvents: {
    navLabel: "Eventos",
    href: "/admin/contenido-en-vivo",
    newHref: "/admin/contenido-en-vivo/nuevo",
    eyebrow: "Sitio",
    title: "Eventos",
    description:
      "Crea una página pública con título, descripción y un botón hacia el álbum o la transmisión.",
    newTitle: "Nuevo evento",
    newDescription:
      "Al publicarlo se genera un enlace para compartir. No aparece en el menú del sitio.",
    newLabel: "Nuevo evento",
    publicListLabel: "Contenido en vivo",
    titleLabel: "Título",
    titlePlaceholder: "Grados Colegio X",
    descriptionLabel: "Descripción",
    buttonLabelLabel: "Texto del botón",
    buttonUrlLabel: "Enlace del botón",
    buttonUrlPlaceholder: "https://",
    buttonUrlHint: "Debe ser un enlace externo completo (https://…).",
    publishedLabel: "Publicado",
    createLabel: "Crear evento",
    saveLabel: "Guardar cambios",
    deleteLabel: "Eliminar evento",
    deleteHint:
      "Se quitará la página pública, el listado y las fotos del almacenamiento.",
    imagesLabel: "Fotos del evento",
    imagesHint:
      "Máximo 5. Se optimizan a WebP liviano para la franja de la página pública.",
    imagesRemoveLabel: "Quitar",
    imagesMaxError: "Puedes subir máximo 5 fotos por evento.",
    empty: "Aún no hay eventos. Crea el primero.",
    publicLinkLabel: "Enlace para el cliente",
    openPublicLabel: "Abrir página",
    editLabel: "Editar",
    tableTitle: "Título",
    tableSlug: "Enlace",
    tableLinkLabel: "Ver página",
    tableLinkDraft: "Aún no publicado",
    tableStatus: "Estado",
    tableActions: "Acciones",
  },
} as const;
