export const adminConfig = {
  toast: {
    created: "Creado exitosamente.",
    updated: "Guardado correctamente.",
    saved: "Guardado correctamente.",
  },
  kit: {
    contentLabel: "Contenido del kit",
    contentPlaceholder: "Ej.: KIT UNO, Incluye, lista de ítems…",
    contentHint:
      "Usa negrita para el nombre del kit y listas con viñetas para lo que incluye.",
    valueLabel: "Valor",
    addLabel: "Agregar kit",
    removeLabel: "Quitar",
    valuePlaceholder: "50.000",
  },
  printLists: {
    navLabel: "Servicios adicionales",
    href: "/admin/impresiones",
    eyebrow: "Landing",
    title: "Servicios adicionales",
    description:
      "Edita tamaños y valores de madera y papel, y al final los kits con texto enriquecido. Las fotos y los títulos de la landing no cambian.",
    nameLabel: "Nombre",
    valueLabel: "Valor",
    addLabel: "Agregar fila",
    removeLabel: "Quitar",
    saveLabel: "Guardar cambios",
    namePlaceholder: "10×15",
    valuePlaceholder: "20.000",
  },
  conditions: {
    navLabel: "Condiciones",
    href: "/admin/condiciones",
    eyebrow: "Landing",
    title: "Condiciones",
    description:
      "Edita el título y el texto de cada condición. El encabezado de la sección no cambia.",
    titleLabel: "Título",
    bodyLabel: "Texto",
    addLabel: "Agregar condición",
    removeLabel: "Quitar",
    saveLabel: "Guardar cambios",
    titlePlaceholder: "Galería",
    bodyPlaceholder: "Describe la condición…",
  },
  team: {
    navLabel: "Equipo",
    href: "/admin/equipo",
    newHref: "/admin/equipo/nuevo",
    eyebrow: "Landing",
    title: "Equipo",
    description:
      "Perfiles que aparecen en la sección Equipo del inicio y en /equipo. Las fotos se guardan en Storage.",
    newTitle: "Nuevo perfil",
    newDescription: "Sube una foto cuadrada o vertical; en el sitio se muestra en círculo.",
    newLabel: "Nuevo perfil",
    publicPageLabel: "Ver sección",
    nameLabel: "Nombre",
    namePlaceholder: "Will Tamara",
    roleLabel: "Cargo o rol",
    rolePlaceholder: "Fotógrafo",
    photoLabel: "Foto",
    photoAltLabel: "Texto alternativo de la foto",
    photoAltPlaceholder: "Will Tamara, fotógrafo",
    photoAltHint:
      "Opcional. Si lo dejas vacío, se usa el nombre para lectores de pantalla.",
    publishedLabel: "Publicado",
    createLabel: "Crear perfil",
    saveLabel: "Guardar cambios",
    deleteLabel: "Eliminar perfil",
    deleteHint: "Se quitará del sitio y la foto se borrará del almacenamiento.",
    empty: "Aún no hay perfiles. Crea el primero.",
    editLabel: "Editar",
    tableName: "Nombre",
    tablePhoto: "Foto",
    tableStatus: "Estado",
    tableActions: "Acciones",
  },
  liveEvents: {
    navLabel: "Eventos",
    href: "/admin/contenido-en-vivo",
    newHref: "/admin/contenido-en-vivo/nuevo",
    eyebrow: "Sitio",
    title: "Eventos",
    description:
      "Crea una página pública con título, descripción y un botón hacia el álbum o la transmisión.",
    newTitle: "Nuevo evento",
    newDescription:
      "Al publicarlo se genera un enlace para compartir. No aparece en el menú del sitio.",
    newLabel: "Nuevo evento",
    publicListLabel: "Contenido en vivo",
    titleLabel: "Título",
    titlePlaceholder: "Grados Colegio X",
    descriptionLabel: "Descripción",
    buttonLabelLabel: "Texto del botón",
    buttonUrlLabel: "Enlace del botón",
    buttonUrlPlaceholder: "https://",
    buttonUrlHint: "Debe ser un enlace externo completo (https://…).",
    publishedLabel: "Publicado",
    createLabel: "Crear evento",
    saveLabel: "Guardar cambios",
    deleteLabel: "Eliminar evento",
    deleteHint:
      "Se quitará la página pública, el listado y las fotos del almacenamiento.",
    imagesLabel: "Fotos del evento",
    imagesHint:
      "Máximo 5. Se optimizan a WebP liviano para la franja de la página pública.",
    imagesRemoveLabel: "Quitar",
    imagesMaxError: "Puedes subir máximo 5 fotos por evento.",
    imagesFeaturedBadge: "Principal",
    imagesFeaturedAction: "Hacer principal",
    imagesFeaturedHint:
      "La foto principal se muestra en la tarjeta del listado público.",
    empty: "Aún no hay eventos. Crea el primero.",
    publicLinkLabel: "Enlace para el cliente",
    openPublicLabel: "Abrir página",
    editLabel: "Editar",
    tableTitle: "Título",
    tableSlug: "Enlace",
    tableLinkLabel: "Ver página",
    tableLinkDraft: "Aún no publicado",
    tableStatus: "Estado",
    tableActions: "Acciones",
  },
} as const;
