export const reservationConfig = {
  /** 0 = domingo … 6 = sábado. Todos los días abiertos por defecto. */
  defaultOpenWeekdays: [0, 1, 2, 3, 4, 5, 6] as const,
  weekdayLabels: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"] as const,
  weekdayLabelsShort: ["D", "L", "M", "M", "J", "V", "S"] as const,
  calendarStatusColors: {
    open: {
      indicator: "#16a34a",
      bg: "#ffffff",
    },
    partial: {
      indicator: "#d97706",
      bg: "#fff7ed",
      text: "#9a3412",
    },
    complete: {
      indicator: "#2f4858",
      bg: "#2f4858",
      text: "#ffffff",
    },
    closed: {
      indicator: "#c4bdb5",
      bg: "#f5f0eb",
    },
  },
  calendarDayLabels: {
    available: "Disponible",
    partial: "Parcial",
    complete: "Completo",
    closed: "Cerrado",
    parametrizationOpen: "Abierto",
  },
  categoryLegend: {
    indicator: "#4a5568",
  },
  hours: {
    startHour: 0,
    endHour: 24,
    stepMinutes: 60,
    allDayValue: "Todo el día",
    pickerEyebrow: "Horario",
    pickerTitle: "Elige las horas",
    pickerHint: "Toca la hora de inicio y luego la de fin para marcar el rango.",
    allDayLabel: "Todo el día",
    allDayHint: "Reserva la jornada completa.",
    allDayUnavailable: "Ya hay una reserva este día.",
    continueLabel: "Continuar con los datos",
    changeTimeLabel: "Cambiar horario",
    selectedLabel: "Horario elegido",
    availableLabel: "Disponible",
    occupiedLabel: "Reservado",
    emptySelectionHint: "Elige un rango para continuar.",
    overlapError: "Ese horario ya está ocupado.",
    requiredError: "Elige un horario para continuar.",
    invalidError: "El horario no es válido.",
    timeLabel: "Horario",
    stepHorario: "Horario",
    stepDatos: "Datos",
    stripTitle: "Horas del día",
    clientWhatsAppAria: (phone: string) => `Abrir WhatsApp de ${phone}`,
  },
  form: {
    clientIdNumberLabel: "Cédula",
    guestCountLabel: "Cantidad de personas",
    planPriceLabel: "Precio",
    amountPaidLabel: "Lo que abona",
    amountRemainingLabel: "Lo que resta",
    priceHint: "Valor en pesos colombianos (COP).",
    imageAuth: {
      legend: "Autorización de imagen",
      hint: "El cliente autoriza el uso de las fotografías en el portafolio y en los medios de CapturasTamara.",
      yesLabel: "Autoriza",
      noLabel: "No autoriza",
      requiredError: "Indica si el cliente autoriza el uso de las imágenes.",
      summaryYes: "Autoriza uso en medios",
      summaryNo: "No autoriza uso en medios",
      contractYes:
        "El cliente autoriza el uso de las imágenes en el portafolio y en contenido publicitario de la marca.",
      contractNo:
        "El cliente no autoriza el uso de las imágenes en el portafolio ni en contenido publicitario de la marca.",
    },
    validation: {
      phone: "El teléfono debe tener solo números (máximo 10 dígitos).",
      email: "Ingresa un correo electrónico válido.",
      clientIdNumber: "La cédula debe contener solo números (6 a 12 dígitos).",
      category: "Selecciona una categoría.",
      subcategory: "Selecciona una subcategoría.",
      plan: "Selecciona un plan.",
      guestCount: "Selecciona la cantidad de personas.",
    },
    confirm: {
      title: "Confirmar reserva",
      description: "Revisa los datos antes de registrar el evento.",
      confirmLabel: "Sí, crear reserva",
      cancelLabel: "Volver al formulario",
    },
  },
  contract: {
    printLabel: "Imprimir contrato",
    preparingLabel: "Preparando contrato…",
    documentTitle: "Contrato de prestación de servicios",
    intro:
      "Entre las partes que se identifican a continuación se celebra el presente contrato de prestación de servicios para la producción y cobertura del evento descrito.",
    providerLabel: "Prestador",
    clientLabel: "Contratante",
    eventLabel: "Evento",
    serviceLabel: "Servicio contratado",
    financialLabel: "Valores acordados",
    clausesTitle: "Cláusulas generales",
    clauses: [
      "El contratante se compromete a realizar los pagos en las fechas acordadas.",
      "Los servicios incluidos corresponden al plan seleccionado y la cantidad de personas indicada.",
      "Cualquier modificación al alcance del servicio deberá acordarse por escrito entre las partes.",
      "En caso de cancelación, aplicarán las políticas de la empresa vigentes al momento de la firma.",
    ],
    signatureProviderName: "Tamara",
    signatureProviderRole: "CapturasTamara",
    signatureClientRole: "Cliente",
    signatureLineLabel: "Firma",
    fileNamePrefix: "contrato",
  },
  calendar: {
    timezone: "America/Bogota",
    eventTitle: (clientName: string, planTitle: string) =>
      planTitle && planTitle !== "—"
        ? `Reserva · ${clientName} · ${planTitle}`
        : `Reserva · ${clientName}`,
    syncedSuffix: "Evento creado en Google Calendar.",
    failedSuffix:
      "La reserva se guardó, pero no se pudo crear en Google Calendar.",
  },
  email: {
    subject: (clientName: string) => `Reserva registrada: ${clientName}`,
    noReplyNotice:
      "Este correo es solo informativo. Por favor no respondas a este mensaje.",
    motto: "Captura tu mejor imagen",
    heading: "¡Reserva registrada!",
    greeting: (name: string) => `Hola ${name},`,
    intro:
      "Registramos tu reserva con estos datos. Te contactaremos para continuar la planificación.",
    detailsTitle: "Detalles de tu reserva",
    outro: "Pronto te contactaremos para continuar con la planificación de tu evento.",
    footerNote: "Con cariño, CapturasTamara",
  },
} as const;
